server:
  port: 8761


spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false #block register itself
    fetch-registry: false #block register itself

---

spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8763/eureka/
  instance:
    hostname: localhost

---

spring:
  config:
    activate:
      on-profile: eureka3

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: 127.0.0.1
